#!/bin/sh

# ビルドトリガファイル
# anzu --> apricot.py ---> build

# chmod 755 anzu
#
# ./anzu build <RecipeFile>
# ./anzu run chrome

# version 0.1.0 (@2015/06/13 19:15)
if [ $# == 1 ]; then
    python apricot.py $1
fi
